---
language: node_js
node_js:
  - '10'
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH="$HOME/.yarn/bin:$PATH"
script:
  - yarn lint
  - yarn test
after_script:
  - yarn coverage && cat coverage/lcov.info | coveralls
